# Copyright (c) OGO Security, Inc.
# SPDX-License-Identifier: MPL-2.0

version: '3'

tasks:
  clean:
    desc: Clean test environment
    cmds:
      - rm -r .task/checksum || ()
  doc:
    desc: Generate documentation
    cmds:
      - terraform fmt -recursive examples
      - make generate
  golint:
    desc: Run golint
    cmds:
      - golangci-lint run
  test:
    desc: Run provider Unit Tests
    cmds:
      - make testacc
