# Copyright (c) OgoSecurity, Inc.
# SPDX-License-Identifier: MPL-2.0

version: '3'

vars:

tasks:
  test:
    desc: Run provider Unit Tests
    cmds:
      - make testacc
  clean:
    desc: Clean test environment
    cmds:
      - rm -r .task/checksum || ()
